// Code generated by counterfeiter. DO NOT EDIT.
package commandfakes

import (
	"os/exec"
	"sync"

	"github.com/BooleanCat/go-command"
)

type Wrap struct {
	Stub        func(*exec.Cmd) command.Cmd
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 *exec.Cmd
	}
	returns struct {
		result1 command.Cmd
	}
	returnsOnCall map[int]struct {
		result1 command.Cmd
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Wrap) Spy(arg1 *exec.Cmd) command.Cmd {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 *exec.Cmd
	}{arg1})
	fake.recordInvocation("Wrapper", []interface{}{arg1})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.returns.result1
}

func (fake *Wrap) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *Wrap) ArgsForCall(i int) *exec.Cmd {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1
}

func (fake *Wrap) Returns(result1 command.Cmd) {
	fake.Stub = nil
	fake.returns = struct {
		result1 command.Cmd
	}{result1}
}

func (fake *Wrap) ReturnsOnCall(i int, result1 command.Cmd) {
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 command.Cmd
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 command.Cmd
	}{result1}
}

func (fake *Wrap) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Wrap) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ command.Wrapper = new(Wrap).Spy
